version: '3.8'
# name: 'DaxaXquad'
services:
    dxm-backend:
        image: 'sam-backend'
        container_name: 'sam-backend'
        build: ./
        stdin_open: true
        tty: true
        restart: on-failure
        ports:
            - '4000:4000'
